name = "YaoBlocksQobj"
uuid = "8d6e117e-3ad9-4058-9567-0848b2080ffe"
authors = ["Arsh Sharma <sharmarsh15@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
IBMQClient = "02860bad-daa6-4506-8736-4a3616c18085"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"

[compat]
Configurations = "0.15, 0.16"
IBMQClient = "0.3"
Yao = "0.6"
YaoBlocks = "0.11"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
